### PR TITLE
feat(arm): AzureContainerInstanceEnvVarSecureValueType

### PR DESCRIPTION
**Pull request by pninib**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

adds a AzureContainerInstanceEnvVarSecureValueType

### Description
The scan_resource_conf function checks if container environment variables in an Azure object are set to secure only (ie, no "value" key is used). If it finds environment variables containing the key "value", the test fails; Otherwise, the test passes

### Fix
*How does someone fix the issue in code and/or in runtime?*

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ChanochShayner — APPROVED** [review]
Very Nice

**Comment by ChanochShayner** [comment]
I have unrelated files in this PR, please remove them.

**Comment by ChanochShayner** [comment]
Closing, feel free to reopen if this PR is still relevant.

**Comment by pninib** [comment]
Can I continue this?

‫בתאריך יום ב׳, 29 ביולי 2024 ב-9:15 מאת ‪ChanochShayner‬‏ <‪
***@***.***‬‏>:‬

**Comment by ChanochShayner** [comment]
Please adjust the `test_container_instance_resources` UT at `tests/bicep/image_referencer/test_runner_azure_resources.py`

two lines - 
```
assert len(bicep_report.resources) == 1
assert len(bicep_report.passed_checks) == 1
```

**Comment by pninib** [comment]
Is it meant that I add these lines to the test file?

**Comment by ChanochShayner** [comment]
> Is it meant that I add these lines to the test file?
No, change the assertion to be 1 instead of 0.

**Comment by pninib** [comment]
I opened a new poll request because I got involved in deleting the pages,
etc.
You can check that the requested change has indeed been made.
The link to the new poll request:
://github.com/bridgecrewio/checkov/pull/6625
<https://github.com/bridgecrewio/checkov/pull/6625>
<https://github.com/bridgecrewio/checkov/pull/6625>



Message ID: ***@***.***>
>
>
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
ללא
וירוסים.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
