### PR TITLE
Update pyyaml to version 5.3.1 for security fix

### PR DESCRIPTION
**Pull request by robeden**
Fixes: #381

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by schosterbarak** [comment]
Thanks @robeden! i'll take a look.   btw, how did you find this one out?

**Comment by robeden** [comment]
@schosterbarak - We use [Snyk](https://snyk.io) at my company and I set it up to scan the project. They (weirdly) don't support Pipfile/Pipfile.lock files right now, but it found it through the kubernetes requirements file importing checkov.

We've hit the pyyaml vulnerability in a lot of our projects, so it was also one I was very familiar with.

**Comment by robeden** [comment]
Just noticed that I missed the Homebrew formula. Working on that now.

**Comment by schosterbarak** [comment]
@robeden the homebrew is auto generated. No need to update it too :)

**Pull request merged**
