### PR TITLE
feat(github): add summary message in github_failed_only output

### PR DESCRIPTION
**Pull request by sourava01**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

Adding checks summary to github_failed_only output table.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Saarett** [comment]
Hi @sourava01 , thanks for the contribution! Could you please share the before and after output examples?

**Comment by sourava01** [comment]
Hi @Saarett, Thanks for your response. I have fixed the errors and here is the output comparison.

## Old:

### terraform_plan scan results:

|    | check_id   | file          | resource                                 | check_name                                      | guideline                                                                                                                                                                                                       |
|----|------------|---------------|------------------------------------------|-------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  0 | CKV2_AWS_6 | /checkov.json | module.s3-bucket-1.aws_s3_bucket.this[0] | Ensure that S3 bucket has a Public Access block | https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/s3-bucket-should-have-public-access-blocks-defaults-to-false-if-the-public-access-block-is-not-attached |
|  1 | CKV2_AWS_6 | /checkov.json | module.s3-bucket-2.aws_s3_bucket.this[0] | Ensure that S3 bucket has a Public Access block | https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/s3-bucket-should-have-public-access-blocks-defaults-to-false-if-the-public-access-block-is-not-attached |

---


## New:

### Terraform Plan Scan Results:

```
Passed Checks: 0, Failed Checks: 2, Skipped Checks: 0
```

| Check ID   | Check Name                                      | Resource                                 | Guideline                                                                                                                                                                                                               | File          |
|------------|-------------------------------------------------|------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------|
| CKV2_AWS_6 | Ensure that S3 bucket has a Public Access block | module.s3-bucket-1.aws_s3_bucket.this[0] | [Link](https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/s3-bucket-should-have-public-access-blocks-defaults-to-false-if-the-public-access-block-is-not-attached) | /checkov.json |
| CKV2_AWS_6 | Ensure that S3 bucket has a Public Access block | module.s3-bucket-2.aws_s3_bucket.this[0] | [Link](https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/s3-bucket-should-have-public-access-blocks-defaults-to-false-if-the-public-access-block-is-not-attached) | /checkov.json |

---

**Comment by Saarett** [comment]
@tsmithv11 Could you PTAL at this output change? The code looks good to me.

**Review by Saarett — APPROVED** [review]

**Review by tsmithv11 — COMMENTED** [review]
Much cleaner output. Looks good. 

@Saarett you may have to help with the last check failure.

**Review by ChanochShayner — APPROVED** [review]

**Comment by Saarett** [comment]
> Much cleaner output. Looks good.
> 
> @Saarett you may have to help with the last check failure.

@tsmithv11 This is the failure:

`You've changed `report.py` file, that contains the contract for checkov input and output. Make sure to stay backwards compatible.
`
I suppose we're fine with it? :)

**Comment by sourava01** [comment]
@Saarett @tsmithv11 
The change is indeed in the `report.py` file. So I guess the check is expected to fail.
Regarding `Make sure to stay backwards compatible.`, I don't think this should be an issue since there are no changes in machine interpreted input or output formats (ex-json)

**Comment by Saarett** [comment]
@sourava01 I agree. We will merge this next week. Thank you for the contribution!

**Pull request merged**
