### PR TITLE
Feat(ansible): add ckv pan 21 pan os bpa check for login banner

### PR DESCRIPTION
**Pull request by epartington**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

Add BPA Check 21 for login banner

Fixes # (issue)

### Description
*login banner is not set or undefined is a failure*

### Fix
*How does someone fix the issue in code and/or in runtime?*

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Saarett** [comment]
@epartington Thanks!
I think you might skip CKV_PAN_19 😄 WDYT about updating the 21 to 19?

**Comment by epartington** [comment]
> @epartington Thanks! I think you might skip CKV_PAN_19 😄 WDYT about updating the 21 to 19?

I skipped it as I have a check written for something that appears to have been removed from the BPA library.  But i wanted to leave the gap for 19 so that If it comes back (I think it should) then I can submit that check in that space.  Its closely related to 18 which is why I left 19 open (it used to be a check but was removed oddly)

**Comment by Saarett** [comment]
@epartington Could you please fix the conflict before I review?

**Comment by epartington** [comment]
> @epartington Could you please fix the conflict before I review?

can you close this, i'll try submitting PR again and not screwing up my PR this time to make sure things go in clean.

**Pull request closed without merging**
