### PR TITLE
Adding brew package for homebrew (OSX)

### PR DESCRIPTION
**Pull request by lfacchinelli**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

This PR adds the ability to install checkov using homebrew on OSX (as requested in #218)
Once merged into master, OSX users should execute:

> $ brew tap bridgecrewio/checkov https://github.com/bridgecrewio/checkov
> $ brew update
> $ brew install checkov

On each release, the formula should be updated to reflect the latest release

### CODE REVIEW

**Comment by schosterbarak** [comment]
@lfacchinelli  thank you! 
I guess that means we should add "brew update" stage on each release. correct? - if yes, i can do that. just verifying since i'm not very familiar with brew

**Comment by lfacchinelli** [comment]
Sorry guys, by mistake pressed the “merge” button in github. Can someone revert it back?

**Comment by lfacchinelli** [comment]
@schosterbarak On each release the user should only run:
> $ brew upgrade checkov 

Brew update only refresh the internal database with references about what formula is available on each tap

Homebrew works pretty much like YUM/APT

**Comment by schosterbarak** [comment]
thank you @lfacchinelli  do you know if there is a way to automate the sync between formula and pipenv? 
that way we won't have to maintain package twice

**Comment by lfacchinelli** [comment]
@schosterbarak Based on what's available in the official documentation, no. 
Maybe a solutions is to add a script that release a new version to pypi (using pipenv) and updates lines 5 and 6 of the homebrew Formula

**Pull request merged**
