### PR TITLE
chore(docker): adding a docker file

### PR DESCRIPTION
**Pull request by jdhornsby**
The resulting image can be used by mounting the terraform files at a location and directing checkov to scan that location:
$ docker container run -v /host/path/tf:/tf <image> -d /tf

The entry point can also be overridden to bash for other uses, such as CI commands:
$ docker container run -i -v /host/path/tf:/tf --entrypoint=/bin/bash <image>

### CODE REVIEW

**Comment by nimrodkor** [comment]
Related to https://github.com/bridgecrewio/checkov/issues/50

**Comment by schosterbarak** [comment]
Thank you @jdhornsby , much appreciated!
when would the entrypoint require override? can you give an example?

**Comment by jdhornsby** [comment]
Sure. When I use the image in GitLab CI, I'll override the entry point so I can run scripts with the results of the scan.

**Comment by schosterbarak** [comment]
Thanks! @jdhornsby docker is now available at: https://hub.docker.com/r/bridgecrew/checkov
Have a great week!

**Pull request merged**
