### PR TITLE
Multiline output support | Update `entrypoint.sh`

### LINKED ISSUE #1648: Multiline output from github-action trimmed
**Describe the bug**
Multiline CHECKOV_RESULTS fails. That is because the set-output notation only works on single line input

**To Reproduce**
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Policy Compliance Evaluation
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: compliance/configs/checkov.config.yaml
          directory: charts/checov-test

       - uses: peter-evans/create-or-update-comment@v1
        name: Create comment
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ steps.checkov.outputs.results }}
            ```
          reactions: '+1'
          token: ${{ secrets.DOCKER_GITHUB_TOKEN }}
```

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: iOS
 - Checkov Version : 2.0.437

**Additional context**
Expected output
```
|----|----------------------------------|-----------------|----------------------------------|----------------------------------------------|-------------|
|  0 | HelloFresh-PodDisruptionBudget-1 | /kube-test.yaml | PodDisruptionBudget.test.utility | PodDisruptionBudget should be greater than 1 |             |
```

fixes: #1644

### PR DESCRIPTION
**Pull request by raghavtan**
Fixes #1648 
Multiline `CHECKOV_RESULTS` fails.  That is because the set-output notation only works on single line input

Example use-case:
```
      - uses: peter-evans/create-or-update-comment@v1
        name: Create comment
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ steps.checkov.outputs.results }}
            ```
          reactions: '+1'
          token: ${{ secrets.DOCKER_GITHUB_TOKEN }}

```

Output:
image
#1648 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by schosterbarak** [comment]
hey @raghavtan  
can you share a link to a repository that has an run with this output?

**Comment by raghavtan** [comment]
> hey @raghavtan
> can you share a link to a repository that has an run with this output?

This use case is currently implemented with a private repository. but can setup this workflow on a public one to provide for a demo (reproduce this issue)

**Comment by schosterbarak** [comment]
thanks @raghavtan a public repo will help

**Comment by raghavtan** [comment]
> thanks @raghavtan a public repo will help

This is created to demo the existing multiline output problem from github actions, because the `set-output` notation only works on single line input

@schosterbarak Please check PR [raghavtan/grata/pull/10](https://github.com/raghavtan/grata/pull/10)

it corresponding action output [check_run_id=3687593578#step:5:24](https://github.com/raghavtan/grata/pull/10/checks?check_run_id=3687593578#step:5:24)

and corresponding comment created [issuecomment-925774894](https://github.com/raghavtan/grata/pull/10#issuecomment-925774894)

**Comment by schosterbarak** [comment]
@raghavtan can you show one with comment that has data (not an empty table) with a sample iac file?

**Comment by raghavtan** [comment]
> @raghavtan can you show one with comment that has data (not an empty table) with a sample iac file?

Not able to get multiline data from the variable `CHECKOV_RESULTS` only the 1st line. 

this can also be replicated with `-o json` where only the 1st line is stored on the step output with `echo "::set-output name=results::$CHECKOV_RESULTS"`

**Comment by raghavtan** [comment]
> @raghavtan can you show one with comment that has data (not an empty table) with a sample iac file?

Also the example PR has the sample IAC file with non empty table as shown in the output above but gets stripped in the comments

**Comment by raghavtan** [comment]
> @raghavtan can you show one with comment that has data (not an empty table) with a sample iac file?

This would not be possible since currently actions (bridgecrewio/checkov)will uses the existing docker file

**Comment by raghavtan** [comment]
@schosterbarak tested comments using implemented ENV VAR (`CHECKOV_RESULTS`) and existing `results` variable (used with `set-output`) 
Reference PR [raghavtan/grata/pull/11](https://github.com/raghavtan/grata/pull/11)

Workflow used:
```
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Policy Compliance Evaluation
        id: checkov
        uses: raghavtan/checkov-action@master
        with:
          config_file: compliance/configs/checkov.config.yaml
          directory: checov-test
          log_level: ERROR

      - uses: peter-evans/create-or-update-comment@v1
        name: Create comment
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ env.CHECKOV_RESULTS }}
            ```
          reactions: '+1'
          token: ${{ secrets.DOCKER_GITHUB_TOKEN }}

      - uses: peter-evans/create-or-update-comment@v1
        name: Create comment
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ steps.checkov.outputs.results }}
            ```
          reactions: '+1'
          token: ${{ secrets.DOCKER_GITHUB_TOKEN }}

```

`JSON` output comments 
- with `CHECKOV_RESULTS` env variable [issuecomment-926157383](https://github.com/raghavtan/grata/pull/11#issuecomment-926157383)
- with `results` variable [issuecomment-926157390](https://github.com/raghavtan/grata/pull/11#issuecomment-926157390)

`github_failed_only` output
- with `CHECKOV_RESULTS` env variable [issuecomment-926158962](https://github.com/raghavtan/grata/pull/11#issuecomment-926158962)
- with `results` variable [issuecomment-926158973](https://github.com/raghavtan/grata/pull/11#issuecomment-926158973)

**Comment by schosterbarak** [comment]
thank you @raghavtan! don't forget to apply for swag at: https://bridgecrew.io/blog/happy-hacktoberfest-2021/

**Pull request merged**
