### PR TITLE
FEATURE: Add support for output to CycloneDX XML (schema version 1.3)

### PR DESCRIPTION
**Pull request by madpah**
Signed-off-by: Paul Horton <phorton@sonatype.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by madpah** [comment]
Thanks for the helpful feedback @gruebel - changes made (and I've learnt some things 👍 )

**Comment by schosterbarak** [comment]
thanks @madpah do you know of an open source viewer for CycloneDX we can test it with?

**Comment by madpah** [comment]
@schosterbarak - official answer from CycloneDX Maintainers:

"The CycloneDX Authoring Tool will eventually fill that role. But haven't had time to work on it. https://github.com/CycloneDX/cyclonedx-authoring-tool

Dependency Track is likely the best solution today although it's not specifically a viewer. It supports most component info, services, Dependency graphs, external references, etc."

Also, use an XML Beautifier.

**Comment by madpah** [comment]
Have rebased from `checkov/master` @gruebel

**Pull request merged**
