### PR TITLE
feat(arm): add FunctionAppsEnableAuthentication - Checking if a certain field exists

### PR DESCRIPTION
**Pull request by rutiNalenger**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

adds a FunctionAppsEnableAuthentication

### Description
I added a test that checks whether a value with a value of true is found under a certain field

### Fix
*How does someone fix the issue in code and/or in runtime?*

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ChanochShayner — COMMENTED** [review]
`FunctionAppsEnableAuthentication ` is already implemented here - https://github.com/bridgecrewio/checkov/pull/6243

**Review by ChanochShayner — APPROVED** [review]
Great Job

**Comment by rutiNalenger** [comment]
update the branch

**Review by lirshindalman — APPROVED** [review]

**Review by tsmithv11 — CHANGES_REQUESTED** [review]

**Review by tsmithv11 — APPROVED** [review]
Looks good! If you can add [`authsettingsV2`](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-authsettingsv2?pivots=deployment-language-arm-template) that would be helpful. You would have to check that if you're looking at auth v1, look at `properties/enabled`, if it's auth v2, look at `properties/platformenabled`.

**Comment by ChanochShayner** [comment]
> Looks good! If you can add [`authsettingsV2`](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-authsettingsv2?pivots=deployment-language-arm-template) that would be helpful. You would have to check that if you're looking at auth v1, look at `properties/enabled`, if it's auth v2, look at `properties/platformenabled`.

@tsmithv11 I don't see any relevant field in `Microsoft.Web sites/config 'web'` for this, just `platform/enabled` in v2.
Am I right?

**Comment by tsmithv11** [comment]
> > Looks good! If you can add [`authsettingsV2`](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-authsettingsv2?pivots=deployment-language-arm-template) that would be helpful. You would have to check that if you're looking at auth v1, look at `properties/enabled`, if it's auth v2, look at `properties/platformenabled`.
> 
> @tsmithv11 I don't see any relevant field in `Microsoft.Web sites/config 'web'` for this, just `platform/enabled` in v2. Am I right?

Yeah, correct, `properties/platform/enabled`

**Pull request merged**
