### PR TITLE
Add Output Results in SARIF Format

### PR DESCRIPTION
**Pull request by ne0z**
This PR based on https://github.com/bridgecrewio/checkov/issues/735 discussion. And It would be great if we have an additional output parameter supporting SARIF.

Changes made:
- Added SARIF Format to Checkov
- Using SARIF schema version 2.1.0

Limitation:
- No start and end column
- No severity level (Warning, Note, None). The default severity level is Error.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by schosterbarak** [comment]
@ne0z thank you. can you please add UT?

**Comment by ne0z** [comment]
@schosterbarak Okay, I will add UT for this PR.

**Comment by fproulx-boostsecurity** [comment]
@ne0z any chance this might be completed in the near future ?

+1 on that feature

**Comment by MaSven** [comment]
I have added a test and also done a rebase on the current master here https://github.com/MaSven/checkov/commit/45f64eac686c4c75e2a3a1d31ee47b9216891ab8 hope this gives this PR new live.

**Comment by ne0z** [comment]
Thanks @MaSven for help in making this PR new live. 

Hi @schosterbarak, is this PR is ready for review?

**Comment by schosterbarak** [comment]
thank you @ne0z @MaSven

**Pull request merged**
