### PR TITLE
Check that database version is MySQL

### PR DESCRIPTION
**Pull request by MooreDerek**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Fix for #2269 Add an attribute check for the database version

### CODE REVIEW

**Review by gruebel — COMMENTED** [review]
nice, looks good 🚀 can you also add a test case, please.

**Comment by gruebel** [comment]
sure 🙂  https://github.com/bridgecrewio/checkov/tree/master/tests/terraform/graph/checks/resources/DisableAccessToSqlDBInstanceForRootUsersWithoutPassword

**Review by nimrodkor — DISMISSED** [review]

**Comment by nimrodkor** [comment]
It seems your new UT is failing:
```
E   AssertionError: 3 != 2 : mismatch in number of results in passed, expected: 3, got: 2
```

**Comment by MooreDerek** [comment]
Weird, will take a look.

**Comment by MooreDerek** [comment]
@nimrodkor Have fixed UT, thanks to some help from @gruebel

**Review by gruebel — APPROVED** [review]
nice, great job 🥇

**Pull request merged**
