### PR TITLE
feat(ansible): add Ansible check for CKV_PAN_4 for PAN-OS DSRI

### PR DESCRIPTION
**Pull request by jamesholland-uk**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sca|secrets|serverless|terraform|general|graph|terraform_plan
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description
New (first) Ansible check for PAN-OS, starting with checking the DSRI (disable server response inspection) flag on firewall rules.

My first contribution to Ansible checks so please let me know if I have not done anything correctly :-)

## New/Edited policies
Added Ansible to existing Terraform CKV_PAN_4

### Description
DSRI removes visibility from the firewall's inspection ([ref](https://live.paloaltonetworks.com/t5/best-practice-assessment/disable-server-response-inspection-bpa-checks/ta-p/298655))

### Fix
N/A

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jamesholland-uk** [comment]
Maybe `PolicyNoDSRI.yaml` should have gone in a `panos` folder?

**Review by gruebel — APPROVED** [review]
nice job 🏆

**Comment by gruebel** [comment]
Only thing, which you forgot is to add it to the test file 😄 
https://github.com/bridgecrewio/checkov/blob/main/tests/ansible/checks/graph_checks/test_yaml_policies.py

**Review by ayajbara — APPROVED** [review]

**Review by bo156 — APPROVED** [review]

**Comment by jamesholland-uk** [comment]
Thank you! 🎉

**Pull request merged**
