### PR TITLE
chore(general): Redefine fail-fast

### PR DESCRIPTION
**Pull request by GerevSec**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

Change Redefine mode to fail-fast in order to improve developers feedback time

Fixes # (issue)

### Description
*Include a description of what makes it a violation and any relevant external links.*

### Fix
*How does someone fix the issue in code and/or in runtime?*

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Saarett** [comment]
Hey @GerevSec , thanks for the contribution 🥂 
One question on my end - why would I use fail-fast over discover mode? Seems like discover mode is fast enough as it is right now, and benefits with more capabilities, [according to the docs](https://docs.redefine.dev/configuration/selection-modes/discover)

**Comment by GerevSec** [comment]
Hey @Saarett, that's a great question. Glad to see that you went straight to the docs!
Before diving in to the modes, I'll do a quick overview of Redefine and it's purpose.

Redefine is a Testing optimization platform that leverages AI to understand which tests are relevant to the code change.
The main benefit is providing faster feedback to the developer shorten the development cycle.

Redefine has 4 modes - 
 - *Discover* - This is used for the initial 2-3 weeks in order to train the model based on the repository. *discover mode does not change the behavior of the testing suite*
 - *Prioritize* - Changes the order of the tests from the most likely to fail to the least likely to fail. The provides lightning fast feedback to developers who use the Redefine application for Slack.
 - *Fail-fast* - Same as prioritize, but also provides the option to stop after a certain time if there are any fails. Since the tests that are most likely to fail run first, this provides faster feedback to all developers (not just those using the Redefine application for Slack). If there are no fails, it will run all the tests, guaranteeing that no fails reach the main branch.
 - *Optimize* - This is the same as Fail-fast, but will stop after the time-limit regardless of if there are fails or not. This mode is aimed at enterprise development organizations that run multiple machines on the same test suite for long periods of time, causing the tests to become a bottleneck in the development for all devs.

We (Redefine) have finished creating the model for checkov, providing 98.99% accuracy on 30s (15% of the UT time). That means that in 98.99% of the PRs, if there's a fail it will be included in the first 30s and the feedback will be provided in 30s (!!!) to the developer.
The other 1.01% of the time all tests will execute before the fails will show, still providing 100% safety and certainty to the main branch and Palo Alto.

Let me know if you have any further questions 👍

**Comment by Saarett** [comment]
@GerevSec This is amazing 💪 Let's see how it works 😄

**Comment by GerevSec** [comment]
Hi @Saarett, I see that bandit is failing on changes unrelated to the code change. I've updated the main-branch as required and it seems to require another approval to run the CI 🤔

**Comment by GerevSec** [comment]
Hi @Saarett, hope you had a great weekend.
Any further steps on my side before we can merge the PR?

**Comment by Saarett** [comment]
@GerevSec Nothing, we will get another reviewer soon and then we'll merge it. Wishing you a great ahead 🙂

**Review by Saarett — APPROVED** [review]
💯

**Review by ChanochShayner — APPROVED** [review]

**Pull request merged**
