### PR TITLE
Fix External-Checks-Dir Incorrect YAML Crash

### PR DESCRIPTION
**Pull request by njgibbon**
Hello,

Raising to resolve user issue: https://github.com/bridgecrewio/checkov/issues/1109

When using `--external-checks-dir` the program will crash if it loads an empty file or it loads a file which can not be serialised to a `dict`.

The later downstream code is resilient to being the wrong type of `dict`. Subsequent methods and functions will try to `get` fields and will fail gracefully if they do not exist or are `None`. However, they are not resilient about having `check_json` passed in to them which is not a `dict`. 

I first starting checking if we were dealing with a `dict` in each case and catching the `AttributeError` exception however I realised this would involve several changes.

This solution is the minimal change to fix the issue and is an improvement.

Arguably we could check for more than it just being a dict `here`. I.e use a helper function to validate that all of the fields we may later want to use exist. However, as I mention, all of the downstream functions are already resilient to some expected fields not existing so I wouldn't want to over-engineer.

**License**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by schosterbarak** [comment]
thanks @njgibbon can we add a UT for it?

**Comment by njgibbon** [comment]
@schosterbarak - yes can do, will look at this

**Comment by njgibbon** [comment]
@schosterbarak  - I've added tests related to the conditions that i've added.

These are the first UTs in this area so there is a lot of room to add more.

**Review by JamesWoolfenden — APPROVED** [review]
LGTM

**Pull request merged**
