### PR TITLE
CKV_AWS_8 - bug fix - check for encryption in all of the block_device…

### PR DESCRIPTION
**Pull request by arielkru**
…s before defining result

fixes: https://github.com/bridgecrewio/checkov/issues/363

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by arielkru** [comment]
Solves #363

**Comment by acdha** [comment]
This PR is causing false-positives on anything with a non-hardcoded value. I have a template which launches instances using a dynamic block (in this case, to force encrypted=true on the volumes declared in that AMI) and that causes this check to fail because it's getting the HCL expression rather than the resolved value:

```
(Pdb) p conf[key]
['${[for bdm in data.aws_ami.cis_amazon_linux2.block_device_mappings : bdm if bdm.device_name != data.aws_ami.cis_amazon_linux2.root_device_name]}']
(Pdb) pprint(conf)
{'ami': ['${data.aws_ami.cis_amazon_linux2.id}'],
 'associate_public_ip_address': [False],
 'count': [1],
 'dynamic': [{'ebs_block_device': {'content': [{'delete_on_termination': [True],
                                                'device_name': ['${ebs_block_device.value["device_name"]}'],
                                                'encrypted': [True],
                                                'iops': ['${ebs_block_device.value["ebs"]["iops"]}'],
                                                'kms_key_id': ['${var.kms_key_id}'],
                                                'snapshot_id': ['${ebs_block_device.value["ebs"]["snapshot_id"]}'],
                                                'volume_size': ['${lookup(local.volume_size_overrides,,ebs_block_device.value["device_name"],,ebs_block_device.value["ebs"]["volume_size"],)}'],
                                                'volume_type': ['${ebs_block_device.value["ebs"]["volume_type"]}']}],
                                   'for_each': ['${[for bdm in '
                                                'data.aws_ami.cis_amazon_linux2.block_device_mappings '
                                                ': bdm if bdm.device_name != '
                                                'data.aws_ami.cis_amazon_linux2.root_device_name]}']}}],
 'ebs_block_device': ['${[for bdm in '
                      'data.aws_ami.cis_amazon_linux2.block_device_mappings : '
                      'bdm if bdm.device_name != '
                      'data.aws_ami.cis_amazon_linux2.root_device_name]}'],
 'iam_instance_profile': ['${var.iam_instance_profile}'],
 'instance_type': ['m5n.large'],
 'metadata_options': [{'http_endpoint': ['enabled'],
                       'http_put_response_hop_limit': [1],
                       'http_tokens': ['required']}],
 'root_block_device': [{'encrypted': [True],
                        'kms_key_id': ['${var.kms_key_id}'],
                        'volume_size': [16]}],
 'subnet_id': ['${var.subnet_ids[count.index % length(var.subnet_ids)]}'],
 'tags': ["${merge(var.tags,{'Name': '${var.name_prefix}-${count.index + "
          "1}'})}"],
 'user_data_base64': ['${base64encode(var.user_data)}'],
 'volume_tags': ["${merge(var.tags,{'Name': '${var.name_prefix}-${count.index "
                 "+ 1}'})}"],
 'vpc_security_group_ids': ['${var.vpc_security_group_ids}']}
```

**Comment by acdha** [comment]
The logic for this appears to have a latent bug, as well: it has a path which sets `all_blocks_encrypted = True` but that value can never be cleared. It looks like that's currently safe because the loop exits early with a failure the first time an unencrypted block is encountered but if that changed in the future you'd have a false-negative if there was ever an encrypted device followed by an unencrypted one.

I would personally favor a simpler structure:

```python
        for key in conf.keys():
            if "block_device" in key and "ephemeral" not in key:
                if conf[key][0].get("encrypted") != [True]:
                    return CheckResult.FAILED

        return CheckResult.PASSED
```

This makes the failure to handle dynamic expressions obvious because `"encrypted" in conf[key][0]` silently fails because that's a valid string-contains check on Python rather than the expected key-in-dictionary check the code assumes but `conf[key][0].get("encrypted")` will get an exception.

**Comment by arielkru** [comment]
Hi @acdha,
Thanks for the input, you're right the check didn't handle properly dynamic blocks.
I created a new PR based on your suggestion: #397, which should solve the problem.

**Pull request merged**
