### PR TITLE
Enrich junit report and add tests

### PR DESCRIPTION
**Pull request by costasko**
Some items inspired by #1059 
 
- Replaces`to_xml_string`
- Include `CheckId` in the check_name
- Add record file_path and file_line_range in the failure outputs if available
- Convert to fstrings
- Added tests

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by gruebel** [comment]
I know, there was an issue with replacing `to_xml_string` the last time I did it. The created package through some errors.

**Comment by costasko** [comment]
Thanks @gruebel. I couldn't replicate it, do you happen to remember what the issue was ? 
I fixed the relative path to the junit xml file, so tests _should_ pass now .

**Comment by costasko** [comment]
The workflow runs the unit tests first, and there's not terragoat report generated. I've split the tests and added it under `integration_tests`, since I noticed there's a `json_report` test as well.

**Review by schosterbarak — APPROVED** [review]
Looks great! thank you so much!

**Pull request merged**
