### PR TITLE
Unpin dpath, update to 2.0.1

### PR DESCRIPTION
**Pull request by robeden**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by schosterbarak** [comment]
Hey @robeden thank you!
What is the scenario that led you into the need for a newer version of dpath?

**Comment by robeden** [comment]
My main tool is an AWS Lambda which has checkov as a pip dependency. I then fork it from the same env. As a result, the dpath used by checkov is the same one I’m required to use.
There are other ways I could do that, so it’s not a huge deal if you don’t want to update for some reason, but I figured it would be good to keep up.

**Comment by robeden** [comment]
Oh, and dpath 2 allows defaults on `get`, so you don’t have to raise a KeyError if an element isn’t found. That was the main functionality I wanted.

**Comment by schosterbarak** [comment]
Hi @robeden this currently breaks internal integrations on our private repos. we'll have to wait for merging this one.

**Comment by robeden** [comment]
@schosterbarak - Understood, thanks for letting me know. Hopefully that tech debt can get paid down at some point.

**Comment by robeden** [comment]
FYI: https://github.com/akesterson/dpath-python/issues/136

**Comment by schosterbarak** [comment]
@tronxd @nimrodkor is it ok to coordinate this for this week releases?

**Review by nimrodkor — COMMENTED** [review]
Hey @robeden !

Sorry for getting to this so late. Just remove the update to the brew formula and we're good :)

**Comment by robeden** [comment]
@nimrodkor - This was on hold because you guys had downstream conflicts. Has that been resolved so you're ready to move forward? If so, this has grown pretty stale so I can resync it.

**Pull request closed without merging**
