### PR TITLE
feat(arm): implement CKV_AZURE_97 for ARM

### PR DESCRIPTION
**Pull request by JamesWoolfenden**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*

Fixes # (issue)

### Description
*Include a description of what makes it a violation and any relevant external links.*

### Fix
*How does someone fix the issue in code and/or in runtime?*

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gruebel — APPROVED** [review]
🍺

**Review by ChanochShayner — APPROVED** [review]

**Comment by mmassey1993** [comment]
Hi,

This merge has now broken my checkov for the things you have tried to resolve. I am now getting errors of CKV_AZURE_97 on my tests asking for encryptionAtHost property to be set to true on my Bicep virtual machine modules, which it already is.

Please can you review the code. Looks like it tries to find the "virtualMachineProfile" property, something which doesnt exist in Bicep. There is a securityProfile property though.

Many thanks

Michael

**Comment by gruebel** [comment]
hey @mmassey1993 thanks for reaching out.

I checked the code and also the Bicep docs. If you define a `Microsoft.Compute/virtualMachineScaleSets` resource, then `securityProfile` is found under `virtualMachineProfile`. If it is a `Microsoft.Compute/virtualMachines` resource, then is just `securityProfile`. Without an example of the resource, which is failing for you I can't say why is failing.

**Comment by mmassey1993** [comment]
Yeah i have that. This is one of the modules that fails now for me on the check:
resource VM 'Microsoft.Compute/virtualMachines@2021-11-01' = {
  name: virtualMachineName
  location: location
  tags: tags
  properties: {
    networkProfile: {
      networkInterfaces: [
        {
          id: networkInterface.id
        }
      ]
    }
    osProfile: {
      computerName: virtualMachineName
      adminUsername: username
      adminPassword: password
    }
    licenseType: 'Windows_Server'
    hardwareProfile: {
      vmSize: 'Standard_D2s_v5'
    }
    securityProfile: {
      encryptionAtHost: true
    }
    storageProfile: {
      osDisk: {
        createOption: 'FromImage'
        managedDisk: {
          storageAccountType: 'StandardSSD_LRS'
        }
      }
      dataDisks: [
        {
          diskSizeGB: 1023
          lun: 0
          createOption: 'Empty'
        }
      ]
      imageReference: {
        publisher: 'MicrosoftWindowsServer'
        offer: 'WindowsServer'
        sku: '2022-datacenter-azure-edition'
        version: 'latest'
      }
    }
  }
}

**Comment by gruebel** [comment]
thanks, found the issue. We check against a string not a boolean. I will prepare a fix for it 🙂

**Pull request merged**
