### PR TITLE
chore: separate S3 client creation

### PR DESCRIPTION
**Pull request by gruebel**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

- moved the S3 client creation to better handle multiprocessing `spawn` mode

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Saarett — APPROVED** [review]
It works like a charm 🍀

**Review by lirshindalman — APPROVED** [review]

**Review by rotemavni — APPROVED** [review]

**Comment by chenrui333** [comment]
this PR actually breaks the homebrew update, https://github.com/Homebrew/homebrew-core/pull/154982 (3.1.0 release build), why does it need credentials?

**Comment by Saarett** [comment]
@chenrui333 Could you please share the full logs?

**Comment by chenrui333** [comment]
This is the error run log

```
==> /opt/homebrew/Cellar/checkov/3.1.0/bin/checkov -f /private/tmp/checkov-test-20231120-22742-1k8j752/test.tf 2>&1
  Error: -20 20:53:26,071 [MainThread  ] [ERROR]  Exception traceback:
  Error: test failed
  multiprocessing.pool.RemoteTraceback: 
  """
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
      result = (True, func(*args, **kwds))
                      ^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line [51](https://github.com/Homebrew/homebrew-core/actions/runs/6938043234/job/18873191365#step:3:52), in starmapstar
      return list(itertools.starmap(args[0], args[1]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/checkov/3.1.0/libexec/lib/python3.12/site-packages/checkov/common/runners/runner_registry.py", line 788, in _parallel_run
      report = runner.run(
               ^^^^^^^^^^^
    File "/opt/homebrew/Cellar/checkov/3.1.0/libexec/lib/python3.12/site-packages/checkov/secrets/runner.py", line 131, in run
      bc_integration.set_s3_client()
    File "/opt/homebrew/Cellar/checkov/3.1.0/libexec/lib/python3.12/site-packages/checkov/common/bridgecrew/platform_integration.py", line 397, in set_s3_client
      raise ValueError("Credentials for client are not set")
  ValueError: Credentials for client are not set
  """
```

**Comment by chenrui333** [comment]
I will log an separate issue on this

**Pull request merged**
