### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by akshatgurnani**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by gruebel** [comment]
currently the used Python version for all CI/CD parts is 3.7, that's why the image also uses 3.7. @nimrodkor is there any plan to upgrade the version to 3.8 or even to 3.9?

**Comment by schosterbarak** [comment]
good call @gruebel 3.7 is used for backward compatibility. 
we can change the container to 3.9 but I don't want to raise the barrier of entrance require the latest python when using pip

**Comment by gruebel** [comment]
@schosterbarak yeah, let's keep the minimum version requirement low and just raise the Docker base image version to `3.9-alpine`
@akshatgurnani can you please adjust the base image version accordingly 🙂

**Review by akshatgurnani — COMMENTED** [review]
updated base image to python: 3.9-alpine

**Comment by akshatgurnani** [comment]
@gruebel I updated it, merge the pull request. 🙂

**Comment by schosterbarak** [comment]
thanks @akshatgurnani don't forget to apply for swag at https://bridgecrew.io/blog/happy-hacktoberfest-2021/

**Pull request merged**
