### PR TITLE
chore: update CycloneDx to version 6.0.0 and bound all dependencies

### PR DESCRIPTION
**Pull request by gruebel**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

- added to all runtime dependencies lower and upper bounds, usually it is between 2 major/minor versions, but both `docker` and `importlib-metadata` released a new major version in last 1-2 weeks. After a few months, they can also be raised accordingly
- additionally I lower/upper bound the `types-xyz` dev dependencies to be in line with their corresponding package
- removed dependency `schema` because it is not in-use anymore
- copied the code from `update-checker` under `common.util`, because it looks pretty much unmaintained, last release in `0.18.0`
- copied the code of `file_sha1sum()` from `cyclonedx-python-lib` because it looks like an internal function and I don't want to rely on it being removed/moved again

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Saarett** [comment]
@gruebel What a great PR 😄 Are you missing the setup.py file?

**Comment by gruebel** [comment]
@Saarett it is there, just hiding at the bottom 😄

**Review by lirshindalman — APPROVED** [review]

**Review by lirshindalman — APPROVED** [review]
nice!

**Review by Saarett — APPROVED** [review]
💯

**Comment by Saarett** [comment]
@gruebel Oh no, please fix the security issue 🙏

**Review by Saarett — CHANGES_REQUESTED** [review]
bandit-security check

**Review by maxamel — APPROVED** [review]

**Review by Saarett — APPROVED** [review]

**Comment by Saarett** [comment]
@gruebel Can we merge it? 😄

**Comment by gruebel** [comment]
Sure, no changes planned from me at the moment, but probably wait till Sunday 😄

**Pull request merged**
