### PR TITLE
feat(terraform): Add ability to define the `guideline` option for all Terraform Resource Checks

### PR DESCRIPTION
**Pull request by cawilson**
# User description
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

## Description

Including the same `guideline` option in the Terraform resource checks `BaseResourceNegativeValueCheck` and `BaseResourceValueCheck`, which passes through the option to the existing option in the `BaseResourceCheck` class.

Updated the associated tests to include setting the `guideline` option in addition to adding missing tests for the `BaseResourceNegativeValueCheck` Terraform resource check class.

This should be a non-breaking change which fills in a gap with the resource checks and setting the `guideline` option.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my feature, policy, or fix is effective and works
- [X] New and existing tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

---

# Generated description

Below is a concise technical summary of the changes proposed in this PR:
<p>Introduce the <code>guideline</code> option to the <code>BaseResourceNegativeValueCheck</code> and <code>BaseResourceValueCheck</code> classes, allowing users to specify guidelines for Terraform resource checks. This enhancement extends the existing <code>BaseResourceCheck</code> class functionality. Additionally, update the test suite to cover the new <code>guideline</code> option, ensuring comprehensive testing for both <code>BaseResourceNegativeValueCheck</code> and <code>BaseResourceValueCheck</code> classes.</p>
    <table><tr><th>Topic</th><th>Details</th><tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/6080?tool=ast&topic=Guideline+Option+Enhancement>Guideline Option Enhancement</a>
        </td><td>Add the <code>guideline</code> option to the <code>BaseResourceNegativeValueCheck</code> and <code>BaseResourceValueCheck</code> classes, enhancing the flexibility of Terraform resource checks.<details><summary>Modified files (2)</summary><ul><li>checkov/terraform/checks/resource/base_resource_value_check.py</li>
<li>checkov/terraform/checks/resource/base_resource_negative_value_check.py</li></ul></details><details><summary>Latest Contributors(2)</summary><table><tr><th>User</th><th>Commit</th><th>Date</th></tr><tr><td>gruebel</td><td>chore-performance-impr...</td><td>July 17, 2023</td></tr>
<tr><td>rotemavni</td><td>Revert-chore-upgrade-d...</td><td>March 19, 2023</td></tr></table></details></td></tr>
<tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/6080?tool=ast&topic=Test+Suite+Update>Test Suite Update</a>
        </td><td>Update tests to include the <code>guideline</code> option, ensuring the new feature is thoroughly tested and validated.<details><summary>Modified files (4)</summary><ul><li>tests/terraform/checks/resource/test_base_resource_check.py</li>
<li>tests/terraform/checks/resource/test_base_resource_dynamic_value_check.py</li>
<li>tests/terraform/checks/resource/test_base_resource_negative_value_check.py</li>
<li>tests/terraform/checks/resource/test_base_resource_value_check.py</li></ul></details><details><summary>Latest Contributors(2)</summary><table><tr><th>User</th><th>Commit</th><th>Date</th></tr><tr><td>yuvalshi0@gmail.com</td><td>fix-general-fixing-hid...</td><td>January 09, 2024</td></tr>
<tr><td>49649760+lirshindalman...</td><td>fix-terraform-check-if...</td><td>October 05, 2023</td></tr></table></details></td></tr></table>This pull request is reviewed by Baz. Join @cawilson and the rest of your team on <a href=https://baz.co/login>(Baz)</a>.

### CODE REVIEW

**Comment by cawilson** [comment]
@SteveVaknin any chance someone would be able to look into this minor change? 🙏🏻

**Comment by cawilson** [comment]
@maxamel any chance someone could look at and provide feedback on this change? 🙏🏻

**Review by bo156 — APPROVED** [review]
Nice work 💯 
@cawilson can you rebase your code from main to retrigger the security-checks? I saw it failed.

**Comment by cawilson** [comment]
> Nice work 💯 @cawilson can you rebase your code from main to retrigger the security-checks? I saw it failed.

Just noticed your response (thank you!). I have merged `main` into my branch and so it should be good to go AFAIK.

**Review by tsmithv11 — APPROVED** [review]

**Pull request merged**
