### PR TITLE
HCL1 transformation attempts and parsing support (stale)

### PR DESCRIPTION
**Pull request by robeden**
This adds the ability to read HCL1 files if the env variable `CKV_ENABLE_HCL1` is set to `yes` (or `1` or `true`). When a terraform file can't be read with the HCL2 parser, the HCL(1) parser is attempted. If that works, there is a transformation process that takes place to convert the data to appear as though it came from the HCL2 parser. This process is by no means perfect (there's a bit of art mixed in with science), but it might be good enough for most circumstances.

The main place there can be ambiguity is that there is no way to tell the different between:
```
foo {
   bar = "baz"
}
```
and
```
foo = {
   bar = "baz"
}
```
... once it has gone through the HCL1 parser. So, there is a bit of educated guessing. I've run it through many test cases and the results have been good, so hopefully it will be good enough for most situations.

Fixes: #681

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by robeden** [comment]
Apparently messed up my pipfile during merge. Will look on the morning...

**Comment by schosterbarak** [comment]
hi @robeden, can you please sync with master? i intend to run this as an experiment this week.

**Comment by robeden** [comment]
@schosterbarak - It's re-merged now.

**Comment by schosterbarak** [comment]
@robeden for some reason it still shows `setup.py` is conflicting

**Comment by robeden** [comment]
@schosterbarak - Ugh, sorry... haven't had my coffee yet and missed that. Looking... ☕

**Comment by robeden** [comment]
No idea what's going on with the build right now. Looks like it's trying to install deps with python 2.7?!? My master branch has gotten quite noisy with merges. I may re-pull a fresh copy and redo this PR and see if that cleans it up because nothing from the change set jumps out at me as the problem. 🤷‍♂️

**Comment by robeden** [comment]
Replaced by #732

**Pull request closed without merging**
