### PR TITLE
fix(cloudformation): KMSKeyWildCardPrincipal modification - Check for wildcards inside of lists

### PR DESCRIPTION
**Pull request by MattJaccino**
My company just found a case of a dev using a wildcard inside of an AWS principal list to evade this rule.  Since the `principal_value` in this code could be either a string or a list, checking for membership as well as equality would prevent the circumnavigation of the rule.

**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sca|secrets|serverless|terraform|general|graph|terraform_plan
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"
# cloudformation: KMSKeyWildCardPrincipal modification - Check for wildcards inside of lists

## Description

My company just found a case of a dev using a wildcard inside of an AWS principal list to evade this rule.  Since the `principal_value` in this code could be either a string or a list, checking for membership as well as equality would prevent the circumnavigation of the rule.

Fixes # (issue)

Ability to skate by the check by placing the wildcard within a list

### Description
It undermines the rule

### Fix
Check for membership as well

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gruebel** [comment]
thanks for the PR, could you also add a resource example here?

**Comment by MattJaccino** [comment]
Hi Anton,

Here's a snippet of a YAML CFN template that would pass the check as it is currently in Checkov even though it contains a wildcarded principal:

```yaml
  SomeKmsKey:
    Type: 'AWS::KMS::Key'
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: 
                - '*' # <-- wildcarded principal without condition
                - 'arn:aws:iam::123456789012:root'
            Action: 'kms:*'
            Resource: '*'
```

**Comment by MattJaccino** [comment]
added a type check to resolve the errors in the tests, but also made me think that a wildcard can still be added if you take advantage of intrinsics in cfn

`!Join [ '', ['', '*' ] ]` would resolve to `*` after processing, but Checkov would just see it as an object.

This could be handled if all intrinsics in templates get "evaluated" prior to scanning, the way you already with with Refs with parameters with default values.

**Comment by gruebel** [comment]
😄 sneaky dev
change looks good, can you also add it as a test?

**Comment by gruebel** [comment]
> added a type check to resolve the errors in the tests, but also made me think that a wildcard can still be added if you take advantage of intrinsics in cfn
> 
> `!Join [ '', ['', '*' ] ]` would resolve to `*` after processing, but Checkov would just see it as an object.
> 
> This could be handled if all intrinsics in templates get "evaluated" prior to scanning, the way you already with with Refs with parameters with default values.

yeah support of evaluating this and also other intrinsic functions would be great, but currently not on our short term roadmap.

**Comment by MattJaccino** [comment]
> 😄 sneaky dev change looks good, can you also add it as a test?

think I got the right file, yeah? added it to `tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-FAILED-AWS-Wildcard.yaml`

**Comment by gruebel** [comment]
yeah, folder looks good, but you also need to adjust the actual test here `tests/cloudformation/checks/resource/aws/test_KMSKeyWildCardPrincipal.py` just increment the failed value by 1 🙂

**Comment by MattJaccino** [comment]
done

**Review by gruebel — APPROVED** [review]
thanks, great jon 🏆

**Comment by gruebel** [comment]
Only thing, which you forgot is to add it to the test file 😄 
https://github.com/bridgecrewio/checkov/blob/main/tests/ansible/checks/graph_checks/test_yaml_policies.py

**Review by Eliran-Turgeman — APPROVED** [review]

**Pull request merged**
