### PR TITLE
fix: bump `cyclonedx-python-lib` to `0.11.*`

### PR DESCRIPTION
**Pull request by madpah**
Signed-off-by: Paul Horton <phorton@sonatype.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by schosterbarak** [comment]
if you'll try to build it locally with 0.11 and run the ci command on local build it explodes- not sure what was changed in cyclone to make it happen

**Comment by madpah** [comment]
Apologises @schosterbarak - missed updating the dependency in `setup.py` too.

**Comment by manuel-sommer** [comment]
@madpah and @schosterbarak do you have a rough estimate when this will be merged? I also have dependencies on this. :+1:

**Comment by madpah** [comment]
@schosterbarak - have rebased this PR from checkov/master to resolve conflicts that had appeared. Let me know if you need anything from me prior to getting this merged!

**Pull request merged**
