### PR TITLE
Replace local formula update with homebrew update

### PR DESCRIPTION
**Pull request by nimrodkor**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Merges flow from #663 to the existing release flow on every push to master

cc @chenrui333

### CODE REVIEW

**Review by schosterbarak — APPROVED** [review]

**Review by chenrui333 — COMMENTED** [review]
by nature the build and release are separate, otherwise it would end up being throttled on the homebrew-core side.

**Comment by chenrui333** [comment]
I think the github tag triggering should be good enough, no? Release on every master build seems little bit overwhelming.

**Comment by schosterbarak** [comment]
@chenrui333 the following configuration ended up with the following failure. any ideas what we did wrong?
image

**Comment by schosterbarak** [comment]
@chenrui333 ?

**Pull request merged**
