### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by schosterbarak**
update k8 docker image to slim - takes less space and fewer vulnerabilities

### CODE REVIEW

**Review by gruebel — APPROVED** [review]
🥇

**Comment by gruebel** [comment]
I tested it and it looks like the `slim` images doesn't have curl installed anymore, so you also need to add it on line 7 after `git`
```Dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends git curl && \
```

**Review by gruebel — CHANGES_REQUESTED** [review]
see comment

**Comment by schosterbarak** [comment]
> see comment

@gruebel PTAL :)

**Review by gruebel — APPROVED** [review]
👍

**Pull request merged**
