### PR TITLE
CKV_GCP_76/update-the-gcp-compute-subnetwork-private-ipv6-google-access-check

### PR DESCRIPTION
**Pull request by parabolic**
This change fixes the issue with the argument `private_ipv6_google_access` in the `google_compute_subnetwork` terraform resource. It accepts true but does no change to the actual setting. Checkov expects true and fails otherwise. You can find more details in the linked issue below.
https://github.com/bridgecrewio/checkov/issues/2979

The tests are passing and I have also created a version and tested it against dummy terraform templates.
**Test Output:**
```sh
$ pipenv run python -m coverage run -m pytest tests/terraform/checks/resource/gcp/test_GoogleSubnetworkIPV6PrivateGoogleEnabled.py 
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.7.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/kikola/Documents/work/checkov, configfile: pytest.ini
plugins: mock-3.7.0, xdist-2.5.0, cov-3.0.0, forked-1.4.0, asyncio-0.18.3
asyncio: mode=legacy
gw0 [1] / gw1 [1]
.                                                                                                                                                                                                           [100%]
================================================================================================ warnings summary =================================================================================================
../../../.local/share/virtualenvs/checkov-b6-xzvGD/lib/python3.7/site-packages/pytest_asyncio/plugin.py:191
../../../.local/share/virtualenvs/checkov-b6-xzvGD/lib/python3.7/site-packages/pytest_asyncio/plugin.py:191
../../../.local/share/virtualenvs/checkov-b6-xzvGD/lib/python3.7/site-packages/pytest_asyncio/plugin.py:191
  /home/kikola/.local/share/virtualenvs/checkov-b6-xzvGD/lib/python3.7/site-packages/pytest_asyncio/plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================================== 1 passed, 3 warnings in 2.29s ==========================================================================================

```

**Changes:**
Adjust the check to match the private_ipv6_google_access argument against the following values:
- ENABLE_OUTBOUND_VM_ACCESS_TO_GOOGLE
- ENABLE_BIDIRECTIONAL_ACCESS_TO_GOOGLE

Adjust the test to check against those 2 values as well.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by gruebel — APPROVED** [review]
thanks, great work 🚀

**Comment by diablo296** [comment]
Why does it only accept two values and not three? For the value true checkov returns failed. Why do not accept value 

`DISABLE_GOOGLE_ACCESS `
But accepts only values
```
ENABLE_BIDIRECTIONAL_ACCESS_TO_GOOGLE
ENABLE_OUTBOUND_VM_ACCESS_TO_GOOGLE
```

**Comment by gruebel** [comment]
@diablo296 because the purpose of the check is `"Ensure that Private google access is enabled for IPV6"` and not disabled.

**Comment by diablo296** [comment]
Ok but what if I want to disable access? Previously if I set true the field was set to `DISABLE_GOOGLE_ACCESS `

**Pull request merged**
