### PR TITLE
Fix false positive for EC2 user data check CKV_AWS_46 (closes #754)

### LINKED ISSUE #754: False positive for CKV_AWS_46: "Ensure no hard coded AWS access key and secret key exists in EC2 user data" 1
The [`string_has_secrets`](https://github.com/bridgecrewio/checkov/blob/master/checkov/common/util/secrets.py) function returns `True` when passed any SHA1 hash. This is problematic because with Terraform resources similar to:

```
resource "aws_instance" "test" {
   // ...
   user_data = filebase64("provision.sh")
}
```

The plan is generated using the hash of the user data, e.g.:

```
10:28:13  #16 29.02       + user_data                    = "d1b0706c4879b31a195d01f3a967e8b35d95cbb7"
```

... which `string_has_secrets` considers as a secret. My suggest would be to have the function return `False` if the user_data is _only_ a SHA1 or MD5 hash

### PR DESCRIPTION
**Pull request by christophetd**
"By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license."

### CODE REVIEW

**Comment by schosterbarak** [comment]
hi @christophetd looks like test_plan_runner is failing. can you take a look before merging?

**Comment by christophetd** [comment]
For sure. The test failure seems unrelated though?

```
=================================== FAILURES ===================================
_____________________ TestRunnerValid.test_runner_root_dir _____________________

self = <tests.terraform.runner.test_plan_runner.TestRunnerValid testMethod=test_runner_root_dir>

    def test_runner_root_dir(self):
        current_dir = os.path.dirname(os.path.realpath(__file__))
        root_dir = current_dir + "/resources"
        runner = Runner()
        report = runner.run(root_folder=root_dir, files=None, external_checks_dir=None,
                            runner_filter=RunnerFilter(framework='all'))
        report_json = report.get_json()
        self.assertTrue(isinstance(report_json, str))
        self.assertIsNotNone(report_json)
        self.assertIsNotNone(report.get_test_suites())
        self.assertEqual(report.get_exit_code(soft_fail=False), 1)
        self.assertEqual(report.get_exit_code(soft_fail=True), 0)
    
>       self.assertEqual(41, report.get_summary()["failed"])
E       AssertionError: 41 != 40
```

**Comment by schosterbarak** [comment]
@christophetd  i belive that due to that change one of the checks is now returning a different result over that plan file

**Comment by mikeurbanski1** [comment]
@christophetd The `aws_instance.web_host` on line ~550 of `tests/terraform/runner/plan/tfplan.json` now passes the check you edited. I modified the expected pass / fail counts (and fixed a mysterious conflict?).

**Comment by mikeurbanski1** [comment]
This is definitely the proudest moment of my git career.

**Review by mikeurbanski1 — APPROVED** [review]

**Pull request merged**
