### PR TITLE
CKV2_GCP_5 fails in a plan scan but passes in the directory scan

### LINKED ISSUE #3271: CKV2_GCP_5 fails in a plan scan but passes in the directory scan
**Describe the issue**
If it is related to an existing check, please note the relevant check ID.
Also, explain the logic for this addition / change.

CKV2_GCP_5. 

Ensure that Cloud Audit Logging is configured properly across all services and all users from a project | Terraform

The plan scan fails and directory scan succeeds.
Due to this block

- cond_type: attribute
      resource_types:
        - google_project_iam_audit_config
      attribute: "audit_log_config.*.exempted_members"
      operator: not_exists
    - cond_type: attribute

This is because a plan outputs exempted_members as any empty list it should make sure the list is empty  OR not existing.

**Examples**

resource "google_project_iam_audit_config" "all-services" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + project = (known after apply)
      + service = "allServices"
      + audit_log_config {
          + exempted_members = []
          + log_type         = "ADMIN_READ"
        }
      + audit_log_config {
          + exempted_members = []
          + log_type         = "DATA_READ"
        }
    }

**Version (please complete the following information):**
 - Checkov Version 2.1.45

**Additional context**

### PR DESCRIPTION
**Pull request by tasha-marreiros**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

## Description

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*

Fixes #3271 
## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my feature, policy, or fix is effective and works
- [X] New and existing tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tasha-marreiros** [comment]
what's the failing check? I can see it's a unit test failure but not sure why!

**Comment by tasha-marreiros** [comment]
So I raised this bug because as a Google partner we are writing code to ensure our customers are writing sane IaC. I saw a bug that was causing our builds to fail while writing Compliance as Code into our pipelines and rather than complain I tried to fix it. However, your documentation support for graph related policies is minimal. Absolutely nothing around testing mechanisms. I don't have enough time in my day to figure this stuff out especially when it comes to python environmentals on a mac. Please can you ensure you support me in knowing why this is failing, allowing me to fix it and updating your documentation in the process.

**Comment by tasha-marreiros** [comment]
Please can you run the workflows on this PR so the unit tests run. I need this fix.

**Comment by gruebel** [comment]
hi @tasha-marreiros thanks for the contribution. I'm curious about the problem with the minimal documentation of YAML based policies. The docs https://github.com/bridgecrewio/checkov/blob/master/docs/6.Contribution/Contribute%20YAML-based%20Policies.md have all the information, which is needed to write a new test and therefore how to update them.

**Review by gruebel — APPROVED** [review]
nice job 🥇

**Comment by tasha-marreiros** [comment]
The only way I could get tests working was through using pycharm and I am a vim user. I don't tend to use IDEs when I develop and I was not able to develop or test outside of an IDE.  You seriously need to document how to set up dependencies. and as we all know python can be testing in the best of situations. I would like to be able to develop in my environment of choice without depending on an IDE. I don't know if that is just me... I am old skool....

**Comment by tasha-marreiros** [comment]
> hi @tasha-marreiros thanks for the contribution. I'm curious about the problem with the minimal documentation of YAML based policies. The docs https://github.com/bridgecrewio/checkov/blob/master/docs/6.Contribution/Contribute%20YAML-based%20Policies.md have all the information, which is needed to write a new test and therefore how to update them.

No that documentation is not enough. You need to tell your clients how to set up their development environments. you need to explicitly explain dependencies. I suffered much pain trying to even get your app running and it broke everything when  I tried to build it. Python as you know especially on mac can be conflictive. Having a succintive setup in a development environment with your users/developers will gain you much traction. Your documentation at the moment is lacking.

**Comment by tasha-marreiros** [comment]
Also I would suggest adding verbosity to your output. When things go wrong the app is pretty silent....

**Comment by gruebel** [comment]
> Also I would suggest adding verbosity to your output. When things go wrong the app is pretty silent....

you can easily increase the verbosity via an env var, which is also documented directly in the main readme.

```python
LOG_LEVEL=DEBUG checkov -d .
```

**Comment by gruebel** [comment]
> > hi @tasha-marreiros thanks for the contribution. I'm curious about the problem with the minimal documentation of YAML based policies. The docs https://github.com/bridgecrewio/checkov/blob/master/docs/6.Contribution/Contribute%20YAML-based%20Policies.md have all the information, which is needed to write a new test and therefore how to update them.
> 
> No that documentation is not enough. You need to tell your clients how to set up their development environments. you need to explicitly explain dependencies. I suffered much pain trying to even get your app running and it broke everything when I tried to build it. Python as you know especially on mac can be conflictive. Having a succintive setup in a development environment with your users/developers will gain you much traction. Your documentation at the moment is lacking. Having said all that. I like your app I saw it before it was commercialised and it was much harder to determine. Since you have taken it over you've already done a good job with it and I am very happy to see the amount of additional GCP support you have included. :)

got it. You can actually find all information regarding initial setup for contributing in the `CONTRIBUTING.md` https://github.com/bridgecrewio/checkov/blob/master/CONTRIBUTING.md 🙂

**Review by nimrodkor — APPROVED** [review]

**Pull request merged**
