### PR TITLE
docker: use py3.10 for base image

### PR DESCRIPTION
**Pull request by chenrui333**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by gruebel** [comment]
Hi, did you try to build them locally and can verify it works?

**Comment by chenrui333** [comment]
@gruebel yes, build and tested out on my machine. This output the same results as the [homebrew test](https://github.com/Homebrew/homebrew-core/blob/master/Formula/checkov.rb#L354-L387).

**Review by gruebel — APPROVED** [review]
I double checked it and since the first patch version of Python 3.10 came out yesterday, happy to merge 💪

**Comment by chenrui333** [comment]
Thanks @gruebel!

**Pull request merged**
