### PR TITLE
Additional check types for Serverless

### PR DESCRIPTION
**Pull request by robeden**
This adds a variety of check types for Serverless corresponding to additional block types:

* custom (BaseCustomCheck)
* layer (BaseLayerCheck)
* package (BasePackageCheck)
* plugin (BasePluginCheck)
* provider (BaseProviderCheck)

Each of these is passed the appropriate data from the corresponding block, if present. In addition a "complete" (BaseCompleteCheck) type has been added which is provided the entire Serverless configuration to allow for additional blocks which may not be caught elsewhere or to assess the overall document.

To facilitate the additional classes, the structure has been changed to mirror the Terraform layout with a check type under the serverless package: `checkov.serverless.checks.<type>...`. The "function" type has been moved into this structure and I *think* I've maintained backwards compatibility by keeping `base_function_check.py` in the `checkov.serverless` package with an import to the new script in `...<function>`. However, this was not easily tested, so I can't completely vouch.

Finally, "enrichment" was extended to copy `stackTags` from the provider block to `tags` in function blocks.

For examples of all check types, see [`tests/serverless/checks/test_check_types.py`](tests/serverless/checks/test_check_types.py)

One additional note: line numbers and content was not straight-forward in two scenarios:

1. For "plugins", line numbers and content could not be pulled out because apparently that doesn't work with lists.
2. For "complete", line numbers are okay (whole file range), but reporting the whole content of the file doesn't seem right.

To deal with these scenarios, the line numbers of the whole file are reported, but no file content is given to the report. This is sub-optimal but for case # 1 the issue is related to the `CfnContextParser` and outside the scope of this change and for # 2, there really isn't a good answer unless the API changes to allow checks to provide back more detail about where the exact problem is located.

Fixes: #478

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by schosterbarak — APPROVED** [review]
Very nice. This will probably enable easier support of multi-cloud SLS. 
@tronxd @nimrodkor @metahertz can you take a look too?

@robeden do you know of OOTB best practices (policies) should be added to checkov after this cool update?

**Comment by robeden** [comment]
@schosterbarak - We’re evaluating that now. I think most are going to be handled by CloudFormation checks of resources. Most of the raw-Serverless config  seems to be reasonable defaults. Checks we’re writing are more company-specific policy. But if I find other cases, I’ll see about including them.

**Review by nimrodkor — COMMENTED** [review]
@robeden Super cool!
I have a question regarding provider confs vs function confs - a lot of the times, the function confs override the ones set in the provider level. In case I'm building a check for a function conf, I'd expect it to check the `default` value from the provider as well as the conf on the function. Is this implemented? I did not see it...

**Comment by robeden** [comment]
@nimrodkor - I'm not entirely sure if it's completely doing all that it needs there. "Enrichment" of functions happens here:
https://github.com/robeden/checkov/blob/sls-check-types-478/checkov/serverless/runner.py#L131
Implementation here:
https://github.com/robeden/checkov/blob/sls-check-types-478/checkov/serverless/parsers/context_parser.py#L39

Most of that pre-existed my changes and copies down the environment and IAM blocks. I added copying of `stackTags` to `tags`.

My guess would be that you're correct and there's more stuff that should be included there, but I'm not sure offhand what it would be. Do you know of any specific items that are missed or is there something else that needs to be handled differently?

Note that there's a test case for that functionality here:
https://github.com/robeden/checkov/blob/sls-check-types-478/tests/serverless/checks/test_check_types.py#L118

**Comment by schosterbarak** [comment]
Thanks @robeden , @nimrodkor and I just synced. Great contribution.

**Pull request merged**
