### PR TITLE
added ability to use environment variable to poplulate SLS_FILE_MASK see Issue #1904

### PR DESCRIPTION
**Pull request by nmrad-91**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nmrad-91** [comment]
Let me know if there is documentation I need to update also.

**Comment by nimrodkor** [comment]
Fixes #1904

**Comment by nimrodkor** [comment]
I definitely think there's docs to update here. @schosterbarak / @metahertz ?

**Comment by nmrad-91** [comment]
So I reviewed the read me file and think that the "Configure an input folder or file" is probably where I add in info about the environment variable. Sound correct?

**Comment by schosterbarak** [comment]
@nmrad-91 can you please add this environment variable to this table at: https://github.com/bridgecrewio/checkov/blob/d3bd3e910f1fa8ff6d9eaef07d933612be7c91a3/docs/2.Basics/Visualizing%20Checkov%20Output.md#environment-variables

**Review by nimrodkor — APPROVED** [review]
I'll handle the docs

**Pull request merged**
