### PR TITLE
fix(terraform): Adding missing null checks

### PR DESCRIPTION
**Pull request by ArjunMenon-bit**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description
- Adding Null checks to run terraform plan using an external json file. Bug reported in issue: #[4473](https://github.com/bridgecrewio/checkov/issues/4473)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ArjunMenon-bit** [comment]
Hi,
I am a new contributor to this project. Whom should I reach out to? To get approvals on this PR.

**Review by gruebel — APPROVED** [review]
Looks good, thanks for the contribution 🏆 

Typically it will be reviewed on working days 🙂

**Comment by ArjunMenon-bit** [comment]
@JamesWoolfenden Could you please approve this PR if it looks good to you.

**Review by JamesWoolfenden — APPROVED** [review]
LGTM

**Comment by ArjunMenon-bit** [comment]
@gruebel  are we good to merge this?

**Pull request merged**
