### PR TITLE
fix(terraform): download external modules with enrichment

### LINKED ISSUE #1665: checkov -f plan.json does not download external terraform modules for enrichment
with a sample config when file is used for tfplan.json
i can see it does not download the external terraform modules ( my scenario is a git source )
i can see when --directory is used it does download the external terraform module

I thought the enrichment should download the external module so the enrichment can work and suppression and so forth
I only use the #comment suppression.

```
download-external-modules: True
evaluate-variables: True
external-modules-download-path: '.external_modules'
file:
  - 'tfplan.json'
repo-root-for-plan-enrichment: '.'
framework: 'all'
no-guide: True
output: 'cli'
skip-fixes: True
skip-suppressions: True
```

### PR DESCRIPTION
**Pull request by fleroux514**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

*Ensures the `--download-external-modules` argument is taken into account when `--repo-root-for-plan-enrichment` is also used.*

Fixes #1665 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gruebel** [comment]
hey @fleroux514 change looks good 💪 would you be able to add UT for it?

**Comment by fleroux514** [comment]
@gruebel Yes I started looking into it but got sidetracked. Will try to find some time to get back to it.

**Review by coffeecoco — COMMENTED** [review]
This actually was an issue in a couple of other issues raised, this did fix the problem for me
+1

**Review by coffeecoco — APPROVED** [review]

**Comment by gruebel** [comment]
hey @fleroux514 still interested in finishing up your PR or should one of us take over?

**Comment by fleroux514** [comment]
@gruebel Please feel free to finish the tests. Still missing some details that I need to figure out and I don't want to hold this one longer. I'll see how you guys do it :)

Thanks

**Review by gruebel — APPROVED** [review]
🙂

**Review by marynaKK — APPROVED** [review]

**Pull request merged**
