### PR TITLE
feat(general): add local cache

### PR DESCRIPTION
**Pull request by gruebel**
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

- adds a local file cache, which currently only caches the public/customer run config
- for easier usage I added a parameterized decorator `ttl_cached`, I initially tried to leverage the `cached` decorator, but it doesn't work properly with persisting it to disk
- performance improvement:
  - get_public_run_config ~ 200ms
  - get_customer_run_config ~2-5sec (depending on the size and a lot of randomness)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ayajbara — APPROVED** [review]

**Review by ChanochShayner — APPROVED** [review]

**Comment by omryMen** [comment]
maybe we should consider saving in the cache - checkov version in case we will have small changes that we will want to clean the cache

**Comment by schosterbarak** [comment]
I might be out of context just stumbled upon this. Consider validating no cross-tenant issues in lambda execution context. :)

**Comment by gruebel** [comment]
@schosterbarak yeah, that's why it is only enabled when the `main.run` method is triggered 😄 so, it is not an issue for us.

**Review by OfekShimko — APPROVED** [review]

**Comment by Saarett** [comment]
@gruebel So.... How are you? 😄

**Comment by pazbechor** [comment]
@gruebel Thanks for the contribution ;)  
Closing this one as conflicts exists & inactivity :) 
Open it in the future if it's still relevant!

**Pull request closed without merging**
