### PR TITLE
Fix - Check - CF - CKV_AWS_16 - Aurora Encryption

### PR DESCRIPTION
**Pull request by njgibbon**
Hello :-)

Issue: https://github.com/bridgecrewio/checkov/issues/586

Adjusting the implementation of CKV_AWS_16 in CloudFormation because Aurora instances should not fail because their encryption is configured differently. 

CF Doc Evidence: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-storageencrypted

This change is to stop the current erroneous failure.

**License**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by nimrodkor — COMMENTED** [review]
@njgibbon Thanks for the contribution!

That seems good, but I wouldn't skip the `BaseResourceValueCheck` so quickly. What do you think about this solution:
Keep the inheritance, and override the `scan_resource_conf` method. In the overriding method, implement the check for aurora as you implemented, and otherwise call the `super`'s `scan_resource_conf`
?

**Comment by njgibbon** [comment]
Hey. Just stabilising the stuff I put in first.

Hmm, so that would be like overriding the method and then conditionally deciding not to use the overridden method in the method its self aha. I think I get it but is that really easier to understand? And in that case couldn't the same argument be made in almost all instances where `BaseResourceValueCheck` get's used?

I can absolutely have a go at it. It would be like a new pattern in (at least) this part of the codebase.

What do ya think?

**Comment by nimrodkor** [comment]
@njgibbon Right. There's an example for it - check out `GoogleCloudDNSSECEnabled`
Yes, that argument can be made for most of the `BaseResourceValueCheck`s that have an exception! 👍

**Comment by njgibbon** [comment]
@nimrodkor  - Cool i'll do that then.

**Comment by njgibbon** [comment]
@nimrodkor Looks pretty clean and I'll similarily use `UNKNOWN` because it's better semantically because just because, yeah, technically it isn't a pass, it's just not a fail.

**Comment by njgibbon** [comment]
@nimrodkor Alright, changed things around :-)

**Review by nimrodkor — APPROVED** [review]
GJ!

**Pull request merged**
