### PR TITLE
docs: update brew install/upgrade instruction

### PR DESCRIPTION
**Pull request by chenrui333**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

relates to https://github.com/Homebrew/homebrew-core/pull/64401

### CODE REVIEW

**Comment by nimrodkor** [comment]
Hi @chenrui333 !

thanks for the contribution, it does seem very very cool. However, the question that's bothering me is how can we update the formula in homebrew? Checkov is still growing, and every release updates the homebrew formula. Implementing this change would mean we will need to update the remote formula every version, right?

**Comment by chenrui333** [comment]
> Hi @chenrui333 !
> 
> thanks for the contribution, it does seem very very cool. However, the question that's bothering me is how can we update the formula in homebrew? Checkov is still growing, and every release updates the homebrew formula. Implementing this change would mean we will need to update the remote formula every version, right?

We (homebrew maintainers as well as contributors) will take care of it, we are pretty active keeping it up to date.

If we run into any issues, we will report into each of the repo.

**Comment by chenrui333** [comment]
There is also another way that you can have it part of the release process. Once I merge my PR, I will share some that insights as well (which is what I have used in tflint)

**Comment by schosterbarak** [comment]
hi @chenrui333  i think this is awesome. I'll merge it first thing tomorrow. 
one thing to notice is that we have a pipeline that auto updates the formula on every build of master (release): https://github.com/bridgecrewio/checkov/blob/master/.github/workflows/build.yml#L166. should we trigger a similar one on each master build on the brew repo?

**Comment by chenrui333** [comment]
very much similar to that, https://github.com/terraform-linters/tflint/blob/master/.github/workflows/homebrew.yml

you need a repo token to PR from bridgecrewio/homebrew-core fork

**Review by nimrodkor — APPROVED** [review]

**Comment by schosterbarak** [comment]
Sweet!

**Pull request merged**
