### PR TITLE
Configuration via file

### LINKED ISSUE #299: Configuration via file
**Describe the solution you'd like**

I feel like it would be powerful to be able to configure `checkov` options via file rather than simply CLI options.

**Additional context**

I've had good experiences working with the yamllint configuration file (https://github.com/adrienverge/yamllint#features). This could be a decent source of inspiration.

### LINKED ISSUE #560: --check and --skip-check lists defined in files
**Is your feature request related to a problem? Please describe.**
We have a need to either define multiple `skip checks` or multiple `checks`. Would be great if we could load them from a file and not define explicitly in the cli param

**Describe the solution you'd like**
`--skip-check-list /path/to/file --check-list /path/to/file`

### PR DESCRIPTION
**Pull request by angatha**
As requested in #299, this is an implementation that allows users to configure checkov via a file instead of using cli arguments.

- [x] wrapping args
- [x] merge configurations (required for combining cli with file)
- [x] support for clearing `checks` and `skip_checks` at least from cli so it is at least possible to execute all checks even if the config exclude some.
- [x] support for YAML as configuration language
- [x] support for configparser as configuration language
- [x] load from a file at a default location
- [x] add cli argument to specify a file
- [x] add cli argument to ignore the file at the default location
- [x] some way to list the default locations

Open questions:

- name and location of the default file

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Resolves #560 and resolves #299

### CODE REVIEW

**Comment by schosterbarak** [comment]
Hey, sent you a message over slack. can we sync there?

**Comment by angatha** [comment]
Closes #299 and maybe #560

**Comment by angatha** [comment]
TODO 

- [] Add tests that assert that the configuration is really used when checkov runs.

**Comment by angatha** [comment]
@schosterbarak can you please have a look? This is ready for review.

**Comment by schosterbarak** [comment]
@angatha this is very nice work. @metahertz let's review it on the next sprint :) looks like an awesome big change

**Comment by angatha** [comment]
@metahertz I updatet the code to the latest master version. There where some new cli arguments which didn't use the tools provided by argparse but used costume code to handle this afterwards.

@schosterbarak  Is there still interest in this PR?

**Comment by schosterbarak** [comment]
hi @angatha thanks for the update. i'll try to get to it this month.

**Comment by floh96** [comment]
@angatha could you please rebase the pr?
@schosterbarak this would be an awesome addition to checkov are you planning on reviewing this soon?

**Comment by angatha** [comment]
Hi @floh96, i can do this but I'm quite busy right now and don't want invest time, if @schosterbarak or @metahertz don't have time to review it in time. Since this is stale for four month now and the original issue was closed, I'm not sure if it is worth the effort, if again, is is not merged. So @schosterbarak is it with to do it?

**Comment by sstaley-sparkpost** [comment]
Hi, I'd just like to link a few additional (repeated)  issues that this relates to which might make it worth merging:
https://github.com/bridgecrewio/checkov/issues/560 
https://github.com/bridgecrewio/checkov/issues/698

**Comment by schosterbarak** [comment]
hi @kartikp10 is working on a new version of this which should be available in the upcoming month

**Comment by njgibbon** [comment]
https://github.com/bridgecrewio/checkov/pull/1248 has now been merged in which deliver this area of functionality. This PR can be closed now.

**Pull request closed without merging**
