### PR TITLE
ISSUE-589 fix for check CKV_GCP_29

### LINKED ISSUE #589: CKV_GCP_29 - Checks failed after GCP resource renamed
**Describe the bug**
Google has renamed the value
`bucket_policy_only ` to `uniform_bucket_level_access`.

When adding the new value in the configuration the check CKV_GCP_29 ( Ensure that Cloud Storage buckets have uniform bucket-level access enabled ) still fails as it is still looking for the old value

**To Reproduce**
1. On tearragoat, add the value `uniform_bucket_level_access = true` and the checks will still fail

**Expected behavior**
The check should pass.

### PR DESCRIPTION
**Pull request by hpapadopoulos**
Fixes #589

### CODE REVIEW

**Comment by metahertz** [comment]
Thanks for the PR @hpapadopoulos 

Tested on the following sample with both `uniform_bucket_level_access = true` and `bucket_policy_only = true` and failure when none are present. LGTM.

```
Passed checks: 1, Failed checks: 1, Skipped checks: 0

Check: CKV_GCP_29: "Ensure that Cloud Storage buckets have uniform bucket-level access enabled"
	PASSED for resource: google_storage_bucket.static-site
	File: /589.tf:1-16
	Guide: https://docs.bridgecrew.io/docs/bc_gcp_gcs_2
```

**Review by nimrodkor — COMMENTED** [review]
@hpapadopoulos That looks really good!

Do you mind commiting test samples?

**Comment by hpapadopoulos** [comment]
Have added the test for this. Could you have a look when you get a minute please?

Thank you

**Comment by schosterbarak** [comment]
@hpapadopoulos LGTM, Thank you!

**Pull request merged**
